name: My First CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Starting CI"

      - name: Enter the name
        run: whoami

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: The End
        run: echo "CI finished"
