name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t day43-app ./docker-practice/day43

      - name: Run Docker container
        run: |
          output=$(docker run --rm day43-app)
          echo "$ouput"

          if [[ "$output" == *"Docker CI is working!"* ]]; then
            echo "Application test passed!"
          else
            echo "Application test failed!"
            exit 1
          fi 
